# -*- coding: utf-8 -*-
'''
Created on 19.07.2012

@author: dom
'''
held = {
    'Name': 'Carisolan Calamar',
    'Rasse': 'Halbelf',
    'Kultur': 'Horasreich',
    'Profession': 'Magier (Halle der Geistreisen zu Belhanka)',
    'Attribute': {
        'MU':12,'KL':15,'IN':15,'CH':12,'FF':14,'GE':12,'KO':13,'KK':11,'BE':0
    },
    'Basiswerte': {
        'MR': 7,
    },
    'Besonderheiten':{
        'Vollzauberer':True,
    },
    'Sonderfertigkeiten':{
        'Kulturkunde':['Horasreich', 'Almada', 'Novadi'],
        'Geländekunde':[],
        'Ortskenntnis':[],
        'Große Meditation': [],
        '':['Nandusgefälliges Wissen']
    },
    'Talente':{
        'Kampf':{
            'Armbrust':{'taw':2},
            'Dolche':{'taw':1,'at':1,'pa':0},
            'Fechtwaffen':{'taw':1,'at':1,'pa':0},
            'Hiebwaffen':{'taw':0,'at':0,'pa':0},
            'Infanteriewaffen':{'taw':4,'at':4,'pa':0},
            'Raufen':{'taw':7,'at':5,'pa':2},
            'Ringen':{'taw':5,'at':1,'pa':4},
            'Säbel':{'taw':2,'at':2,'pa':0},
            'Stäbe':{'taw':10,'at':3,'pa':7},
            'Wurfmesser':{'taw':0},
        },
        'Körper':{
            'Athletik':{'taw':6},
            'Klettern':{'taw':7},
            'Körperbeherrschung':{'taw':7},
            'Reiten':{'taw':5},
            'Schleichen':{'taw':4},
            'Schwimmen':{'taw':5},
            'Selbstbeherrschung':{'taw':6},
            'Sich Verstecken':{'taw':4},
            'Singen':{'taw':3},
            'Sinnenschärfe':{'taw':5},
            'Tanzen':{'taw':4},
            'Zechen':{'taw':4},
        },
        'Gesellschaft':{
            'Betören':{'taw':4},
            'Etikette':{'taw':7},
            'Gassenwissen':{'taw':3},
            'Lehren':{'taw':3},
            'Menschenkenntnis':{'taw':7},
            'Überreden':{'taw':7},
        },
        'Natur':{
            'Fährtensuchen':{'taw':2},
            'Fesseln/Entfesseln':{'taw':2},
            'Orientierung':{'taw':5},
            'Wildnisleben':{'taw':5},
        },
        'Wissen':{
            'Anatomie':{'taw':0},
            'Brettspiel':{'taw':3},
            'Geographie':{'taw':10},
            'Geschichtswissen':{'taw':10},
            'Götter/Kulte':{'taw':8},
            'Magiekunde':{'taw':14},
            'Mechanik':{'taw':10, 'Spezialisierungen':['Magomechanik']},
            'Pflanzenkunde':{'taw':2},
            'Philosophie':{'taw':3},
            'Rechnen':{'taw':8},
            'Rechtskunde':{'taw':4},
            'Sternkunde':{'taw':4},
            'Sagen/Legenden':{'taw':2},
            'Tierkunde':{'taw':3},
        },
        'Sprachen':{
            'Bosparano':{'taw':12},
            'Garethi':{'taw':16, 'Typ':'Muttersprache', 'Dialekt':'Horati'},
            'Isdira':{'taw':8},
            'Tulamidya':{'taw':15, 'Typ':'Lehrsprache'},
            'Ur-Tulamidya':{'taw':6},
            'Rssahh':{'taw':9},
        },
        'Schriften':{
            'Isdira/Asdharia':{'taw':6},
            'Kusliker Zeichen':{'taw':10},
            'Tulamidya':{'taw':7},
            'Geheiligte Glyphen von Unau':{'taw':6},
            'Ur-Tulamidya':{'taw':6},
        },
        'Handwerk':{
            'Ackerbau':{'taw':1},
            'Alchimie':{'taw':2},
            'Heilkunde Wunden':{'taw':0},
            'Holzbearbeitung':{'taw':0},
            'Kochen':{'taw':0},
            'Lederarbeiten':{'taw':1},
            'Malen/Zeichnen':{'taw':4},
            'Schneidern':{'taw':0},
            'Winzer':{'taw':1},
        }
    },
    'Magische Sonderfertigkeiten': {
        'Merkmale': [
            'Eigenschaften',
            'Telekinese',
            'Metamagie',
        ],
        'Repräsentationen': [
            'Magier'
        ],
        'Allgemein': [
            'Astrale Meditation',
            'Große Meditation',
            'Regeneration I',
            'Regeneration II',
            'Zauberkontrolle',
        ]
    },
    'Magische Vorteile': [
        'Akademische Ausbildung (Magier)',
        'Begabung für Zauber (Animatio, Motoricus, Transversalis)',
        'Vollzauberer',
        'Wesen der Nacht II',
    ],
    'Magische Nachteile': [
        'Feste Gewohnheit (Barfuß zaubern)',
        'Körpergebundene Kraft',
        'Wahrer Name'                           
    ],
    'Zauber': {
        'Analys':{'taw':3, 'hauszauber':True},
        'Animatio':{'taw':9, 'begabt':True, 'hauszauber':True}, 
        'Adlerauge':{'taw':0},
        'Applicatus':{'taw':8, 'hauszauber':True},
        'Arcarnovi':{'taw':0, 'hauszauber':True},
        'Armatrutz':{'taw':7},
        'Attributo':{'taw':7},
        'Axxeleratus':{'taw':7, 'hauszauber':True},
        'Balsam':{'taw':7},
        'Band und Fessel':{'taw':0},
        'Bannbaladin':{'taw':2},
        'Bewegung stören':{'taw':3},
        'Blitz':{'taw':4},
        'Custodosigill':{'taw':0},
        'Destructibo':{'taw':0, 'hauszauber':True},
        'Firnlauf':{'taw':3},
        'Flim Flam':{'taw':6},
        'Foramen':{'taw':7, 'hauszauber':True},
        'Fulminictus':{'taw':7},
        'Gardianum':{'taw':6},
        'Gedankenbilder':{'taw':7, 'hauszauber':True},
        'Hellsicht trüben':{'taw':0},
        'Illusion auflösen':{'taw':0},
        'Invocatio minor':{'taw':0},
        'Körperlose Reise':{'taw':3},
        'Leib des Windes':{'taw':2, 'repräsentation':'Elf'},
        'Magischer Raub':{'taw':1},
        'Manifesto':{'taw':3},
        'Memorans':{'taw':0},
        'Motoricus':{'taw':15, 'begabt':True, 'hauszauber':True},
        'Movimento':{'taw':7, 'repräsentation':'Elf'},
        'Objectovoco':{'taw':0},
        'Objekt entzaubern':{'taw':0, 'hauszauber':True},
        'Oculus Astralis':{'taw':5},
        'Odem Arcarnum':{'taw':10},
        'Paralysis':{'taw':8},
        'Penetritzzel':{'taw':0},
        'Pentagramma':{'taw':0, 'hauszauber':True},
        'Psychostabilis':{'taw':0},
        'Reversalis':{'taw':3, 'hauszauber':True},
        'Sapefacta':{'taw':4},
        'Sensibar':{'taw':1},
        'Transversalis':{'taw':10, 'begabt':True, 'hauszauber':True},
        'Unitatio':{'taw':7, 'hauszauber':True},
        'Visibili': {'taw':3},
        'Weihrauchwolke':{'taw':3},
        'Xenographus':{'taw':0},
    }
        
}